import { Button, Grid, Checkbox, FormControlLabel, TextField, Box, MenuItem } from "@mui/material";
import EnhancedTextField from "./components/EnhancedTextField";
import { useEffect, useState } from "react";
import { createImageGivenOpportunity, createImagePromptFromForm } from "../../functions/OpenAi";

const AutoGenerated = (props) => {
    const [imageURLs, setImageURLs] = useState([]);
    const [imagesLoading, setImagesLoading] = useState(false);
    const [promptUsed, setPromptUsed] = useState("");
    const [promptLoading, setPromptLoading] = useState("");

    useEffect(() => {
        setPromptUsed(props.formData.title || "A cute tabby playing the guitar");
    }, []);

    // Generate a prompt from the form provided
    const generatePromptGivenFormData = async () => {
        setPromptLoading(true);
        console.log(props.formData);
        await createImagePromptFromForm(props.formData)
            .then((imagePrompt) => {
                if (imagePrompt) {
                    setPromptUsed(imagePrompt);
                    console.log("Improved image prompt: ", imagePrompt);
                } else {
                    console.log("Error passing form content!");
                }
            })
            .finally(() => {
                setPromptLoading(false);
            });
    };

    // Use Dall E 2 to generate prompt images
    const generateImagesAutomatically = async () => {
        setImagesLoading(true);
        console.log("promptUsed: ", promptUsed);
        await createImageGivenOpportunity(promptUsed)
            .then((urls) => {
                if (!urls) {
                    setImagesLoading(false);
                    console.log("Error loading images!");
                    return;
                }
                console.log("urls: ", urls);
                setImageURLs(urls.map((item) => item.url));
            })
            .finally(() => {
                setImagesLoading(false);
            });
    };

    useEffect(() => {
        console.log("Used Urls: ", imageURLs);
    }, [imageURLs]);

    return (
        <Box sx={{ width: "50%", flexDirection: "column" }}>
            <Box
                sx={{
                    margin: "10px",
                    borderBottom: "1px solid",
                    borderColor: "divider",
                    display: "flex",
                    justifyContent: "center",
                    flexDirection: "column",
                    alignItems: "center",
                }}
            >
                <Box
                    sx={{
                        margin: "10px",
                        borderBottom: "1px solid",
                        borderColor: "divider",
                        display: "flex",
                        justifyContent: "center",
                        width: "100%",
                    }}
                >
                    <TextField
                        margin="normal"
                        name="prompt"
                        label="Prompt for image creation"
                        value={promptUsed}
                        onChange={(e) => {
                            setPromptUsed(e.target.value);
                        }}
                        fullWidth
                    />
                    <Button onClick={generatePromptGivenFormData}>↻</Button>
                </Box>
                <Box
                    sx={{
                        margin: "10px",
                        borderBottom: "1px solid",
                        borderColor: "divider",
                        display: "flex",
                        justifyContent: "center",
                    }}
                >
                    {imagesLoading ? (
                        <img src={process.env.PUBLIC_URL + "/assets/loading_inline.gif"} width="152.5" height="36.5" />
                    ) : (
                        <Button onClick={generateImagesAutomatically}>Generate Images</Button>
                    )}
                </Box>
                <Box
                    sx={{
                        display: "grid",
                        gridTemplateColumns: "repeat(2, 1fr)",
                        gap: "10px",
                    }}
                >
                    {imageURLs.map((image_URL, index) => (
                        <Box
                            key={index}
                            sx={{
                                width: "100%", // Adjust the width as needed
                                maxHeight: "300px",
                                overflow: "hidden",
                            }}
                        >
                            <img
                                src={image_URL}
                                style={{
                                    width: "100%",
                                    objectFit: "cover",
                                    objectPosition: "center",
                                }}
                            />
                        </Box>
                    ))}
                </Box>
            </Box>
            {props.childElements}
        </Box>
    );
};

export default AutoGenerated;
